drop table cargo if exists;
drop table escolaridade if exists;
drop table estados if exists;
drop table estado_civil if exists;
drop table situacao_membro if exists;
drop table igreja if exists;
drop table membro if exists;

create table cargo (
	id integer not null, 
	descricao varchar(255), 
	primary key (id)
);
create table escolaridade (
	id integer not null, 
	descricao varchar(255), 
	primary key (id)
);
create table estados (
	sigla varchar(2) not null, 
	nome varchar(70) not null, 
	primary key (sigla)
);
create table estado_civil (
	id integer not null,  
	descricao varchar(255), 
	primary key (id)
);
create table situacao_membro (
	id integer not null,  
	descricao varchar(255), 
	primary key (id)
);
create table igreja (
	id bigint generated by default as identity, 
	data_criacao timestamp, 
	data_modificacao timestamp, 
	version bigint, 
	bairro varchar(60), 
	cep integer, 
	cidade varchar(60), 
	cnpj varchar(14), 
	data_fundacao date not null, 
	dirigente varchar(70) not null, 
	email varchar(255), 
	estado_sigla varchar(2) not null, 
	nome varchar(70) not null, 
	site varchar(255), 
	telefone varchar(11), 
	sede_id bigint, 
	primary key (id)
);
alter table igreja add constraint FKsldkwyg2ftbw8b8i1ghrexps6 foreign key (sede_id) references igreja;
create table membro (
	id bigint generated by default as identity, 
	data_criacao timestamp, 
	data_modificacao timestamp, 
	version bigint, 
	bairro varchar(60), 
	cargo_id integer, 
	cep integer, 
	cidade varchar(60), 
	conjuge varchar(255), 
	cpf varchar(11), 
	data_batismo date, 
	data_casamento date, 
	data_nascimento date, 
	email varchar(255), 
	endereço varchar(70), 
	escolaridade_id integer, 
	estado_sigla varchar(2) not null, 
	estado_civil_id integer, 
	nacionalidade varchar(255), 
	naturalidade varchar(255), 
	nome varchar(70) not null, 
	nome_mae varchar(70), 
	nome_pai varchar(70), 
	pais varchar(60), 
	rg varchar(14), 
	situacao_id integer, 
	telefone_celular varchar(11), 
	telefone_comercial varchar(11), 
	telefone_residencial varchar(11), 
	igreja_id bigint, 
	primary key (id)
);
alter table membro add constraint FKsd3twkt0whk5gb4m8g2qdj3xd foreign key (igreja_id) references igreja;
